### ISSUE TITLE
Использование при SSR

### ISSUE THREAD

**Issue by Skamnoel** [sberdevices/assistant-client#148]
Есть ли дока как правильно использовать библиотеку при генерации статических страниц ? 
При попытке сделать приложение на nextJS сталкиваюсь с ошибкой из-за обращений к window/alert внутри createAssistant и createSmartappDebugger:

https://github.com/sberdevices/assistant-client/blob/6f1f6f1a9e95fcd14a42ce5a7818e900a6a09f7e/src/index.ts#L348
https://github.com/sberdevices/assistant-client/blob/6f1f6f1a9e95fcd14a42ce5a7818e900a6a09f7e/src/index.ts#L114

![image](https://user-images.githubusercontent.com/14060719/124595258-78875700-de69-11eb-963a-10ebb294c33b.png)

**Comment by sasha-tlt** [comment]
Доки нет, и, кажется, на сервере не получится использовать assistant-client. Просто спрячьте за ифом импорт.

**Comment by Skamnoel** [comment]
Ясно, спасибо.
