### ISSUE TITLE
Добавить метод sendText у AssistantHost

### ISSUE THREAD

**Issue by vak1n** [sberdevices/assistant-client#194]
В новых версиях прошивки у AssistantHost появится метод sendText

Можем ли добавить его `sendText?: (text: string) => void;` в типах?

**Comment by sasha-tlt** [comment]
Можем, этот метод отправляет текст в навык?

**Comment by vak1n** [comment]
Супер!
и тогда лучше так `sendText?: (message: string) => void;`
