### ISSUE TITLE
Добавить возможность узнавать, что ассистент закончил озвучивать TTS

### ISSUE THREAD

**Issue by subnetsRU** [sberdevices/assistant-client#62]
Хотелось бы как-то получать инфу о том, что ассистент закончил озвучивать TTS. В том числе если пользователь прервал его ответ по кнопке.

Для чего ? Для того, чтобы в canvas могло выстрелить некое действие.

**Comment by Turanchoks** [comment]
Извините за долгий ответ.
Лучше продублировать этот запрос в https://github.com/sberdevices/salute-issues, поскольку assistant client лишь клиент для ассистента, и в первую очередь это необходимо реализовать на стороне нативной платформы. Мы сейчас обсуждаем варианты, какие состояния лавашара и как мы будем пробрасывать в канвасы, как только определимся – обязательно сообщим.

**Comment by awinogradov** [comment]
https://github.com/sberdevices/salute-issues/issues/140

**Comment by subnetsRU** [comment]
Упсс... как-то я проспал ответ :( Прощу прощения.
